#ifndef __KEYLOGGER_ERROR_H
#define __KEYLOGGER_ERROR_H

#define KEYLOGGER_NO_ERROR 0x0
#define KEYLOGGER_ERROR_CREATE_FILE 0x1
#define KEYLOGGER_ERROR_GET_APPDATA 0x2
#define KEYLOGGER_ERROR_CREATE_THREAD 0x3
#define KEYLOGGER_ERROR_SET_HOOK 0x4
#define KEYLOGGER_ERROR_FOCUS_TITLE 0x5

#endif